### ISSUE TITLE
First issue 

### ISSUE THREAD

**Issue by YezikTech** [datteroandrea/banedroid#4]
We're not doing enough :)

Team up with me https://banedroid.com

**Comment by YezikTech** [comment]
Second issue:
don't show your cards

**Comment by datteroandrea** [comment]
This was a project I worked on when I was around 16/17 years old and I don't maintain it anymore since I moved into the corporate world, specifically in the field of web development.

If anyone is interested in working on this project of mine feel free to do so and fork the repository! I also do not take responsabilities for any misuse of this application or any similar one since it can have serious legal repercussions.

As I have said this was a passion project and a way for myself to explore the Android ecosystem while also showing my skills.
